export const CHANGE_PLAY_STATUS = 'CHANGE_PLAY_STATUS'

export const CHANGE_CURRENT_LIST = 'CHANGE_CURRENT_LIST'

export const CHANGE_CURRENT_SONG = 'CHANGE_CURRENT_SONG'

export const CHANGE_PAUSED = 'CHANGE_PAUSED'

export const CHANGE_PERCENT = 'CHANGE_PERCENT'
